# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: checkout
  displayName: checkout image
  jobs:  
  - job: checkout
    displayName: checkout
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: SSH@0
        inputs:
          runOptions: 'commands'
          commands: 'uname'
          readyTimeout: '20000'

- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'myDocker'
        repository: 'kanisara/app'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
